name: Deploy Angular Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      # 3. Dependencies installieren
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      # 4. Angular Build mit korrektem base-href
      - name: Build Angular project
        working-directory: ./Frontend
        run: npm run build -- --output-path=dist/frontend --base-href /NarroHome/

      # 5. Deploy zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./Frontend/dist/frontend/browser
